---
- hosts: app_servers
  become: true
  tasks:
   - name: stopping the firewall 
     service: 
         name: firewalld
         state: stopped
   - name:
     get_url:
         url: https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm
         dest: /home/ansible/icinga-rpm-release-7-latest.noarch.rpm
         mode: 0777
   - name: setup icinga2 repo
     yum:
         name: /home/ansible/icinga-rpm-release-7-latest.noarch.rpm
         state: present
   - name: install the latest version of Apache
     yum:
       name: 
         - httpd
         - epel-release
         - wget 
         - curl
         - php
         - php-gd
         - php-intl
         - php-ldap
         - php-ZendFramework
         - php-ZendFramework-Db-Adapter-Pdo-Mysql
         - icinga2
         - nagios-plugins-all
         - icinga2-ido-mysql
         - icingaweb2
         - icingacli
         - icingaweb2-selinux
         - mariadb
         - mariadb-server
       state: latest
     notify:
       - start icinga2
   - name: find and replace
     lineinfile:
         path: /etc/php.ini
         regexp: '^;date.timezone'
         insertafter: '^;date.timezone ='
         line: date.timezone = "Asia/Kolkata"
   - name: mariadb intial setup 
     script: ./script.sh 
     notify: 
       - start httpd
   - name: Ansible Insert multiple lines using blockinfile
     blockinfile:
         dest: /etc/icinga2/features-available/ido-mysql.conf
         block: |
           user = "icinga"
           password = "icinga"
           host = "localhost"
           database = "icinga" 
         backup: yes
   - name: Enable Command Feature icinga2 
     command: icinga2 feature enable command
   - name: adding apache2 user to group sudo
     user:
         name: apache
         groups: icingacmd
         append: yes
  handlers:
   - name: start httpd
     service: 
         name: httpd
         state: restarted
   - name: start mariadb
     service:
         name: mariadb
         state: restarted
   - name: start icinga2
     service:narendran07-patch-1narendran07-patch-1play.yml
         name: icinga2
         state: restarted




REF:
https://www.vultr.com/docs/how-to-install-icinga-2-and-icinga-web-2-on-centos-7
